### ISSUE TITLE
how doe the code work in case of successive elements of the same value 

### ISSUE THREAD

**Issue by aabdelka** [samirinux/longest-run#1]
if input list L=[2,2,2,3,4,5]. Assume we start with toggleCheck = True, then we will check if L[1] > L[0]. If not then L[1] is appended to mono_array and toggleCheck = False. Then then next check (if  not toggleCheck == True) and L[1] will be appended AGAIN to mono_array.

Is this understanding correct ?

**Comment by samirinux** [comment]
Handling of this case was missing.
I fixed the bug and added several tests to cover such cases.
If L[1] == L[0], we check if the length current_mono is > 1. if so append the current monotonic list to the list of found monotonic lists, empty the current monotonic list and append to it the current element and continue comparing with next element.
 
The latest commit contains the fix.
